version: '3.8'

services:
  mtogo.orders:
    container_name: mtogo-orders
    image: mtogo.orders
    build:
      context: .
      dockerfile: src/Orders.Web/Dockerfile
    ports:
      - "8085:80"
    networks:
      - kafka

networks:
  kafka:
    external: true